pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'cd server && npm install'
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    // Skipping Jest tests
                    echo 'Skipping unit tests...'
                }
            }
        }
        stage('Build Application') {
            steps {
                script {
                    sh 'cd server && npm run build-dev'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'scanner'
                    withSonarQubeEnv {
                        sh 'cd server && ${scannerHome}/bin/sonar-scanner'
                    }
                }
            }
        }
    }
}
